### ISSUE TITLE
Modifying ASL

### ISSUE THREAD

**Issue by jhlink** [emoticol/emoticol#4]
ASL sure, but I think it could be even better. 
Maybe, "Yo" like in the Yo app? 

There's a whole plethora of commands here. 

http://www.netlingo.com/acronyms.php

**Comment by andycochran** [comment]
This is a holdover from AOL Instant Messenger. You'd type `asl` and it'd swap in a little question mark/ASL icon. Makes less sense across disparate text-based communication systems.

**Comment by jhlink** [comment]
I agree. Closing issue.

**Comment by andycochran** [comment]
Oh, maybe my sentiment was confusing. I'm for changing ASL. It's confusing. Something like `:|?` might be better.

**Comment by jhlink** [comment]
Oh okay! Now I understand what you're saying! 

I was wanted to change asl due to its negative connotations from its early usage.

**Comment by andycochran** [comment]
Yeah, ASL is offensive. I think back in the day we kinda repurposed it to strip its power. But that was in a closed small network. Keeping it now in this public repo would be crass.

**Comment by jhlink** [comment]
Hmm.. What about :S or :?
I think :|? could be a good replacement. What do you think @bakerface , @gillspice ?

**Comment by andycochran** [comment]
:|

**Comment by gillspice** [comment]
:|

**Comment by andycochran** [comment]
@gillspice Any thoughts on this?

**Comment by gillspice** [comment]
eh, no one will remember what it was originally for.

**Comment by rbultman** [comment]
ASL means nothing to me in all senses.  Every time I see it I have to check the protocol document to see what is means.  I'd rather use 'sup', 'yo', or pull something from CB or ham land.

**Comment by gillspice** [comment]
Add a new command, why deprecate ASL?  It has history, the intentional re-purposing of a bygone icon.

**Comment by rbultman** [comment]
I never said deprecate.

**Comment by gillspice** [comment]
The title of this thread is "Modifying ASL"

**Comment by rbultman** [comment]
I'm out.

**Comment by andycochran** [comment]
I think `:|?` is better. I remember what `ASL` was originally for _and_ what we repurposed it to mean in our tiny private community. But the potential for misunderstanding is risky in public conversation. I don't like (or see the merit in) its history.

**Comment by MylesCaley** [comment]
Urban Dictionary... this chat is actually great.

asl 
What stupid people say on chats to learn who you are and where you live so they can come to your house with a chainsaw and kill you.
bobiscool:hey hi hey lolololoollll 
iamsohot:hi 
bobiscool:asl 
iamsohot:49/f/nebraska 
bobiscool:6/m/america 
iamsohot:kool wats ur name 
bobiscool:bobiscool 
iamsohot:no ur reel name 
bobiscool:bobby jimson 
iamsohot:wana kis 
bobiscool:ya 
iamsohot:smooch 
bobiscool:smooch 
iamsohot:lol!!!1111 i g2g c u bye 
bobiscool:bye 
iamsohot:wat is ur adres 
bobiscool:464 cinnamon way 
iamsohot:k bye 

The next day Bobby's parents went to his room to see how he was doing,and found his head chopped off.Poor Bobby.

**Comment by gillspice** [comment]
I know how to satisfy everyone, lets change asl to (?) which was the hotkey for the original AOL asl icon, if memory serves.
